import { Injectable } from '@angular/core';
import { Observable, of, delay } from 'rxjs';

export interface DynamicTopic {
  id: string;
  title: string;
  isRead: boolean;
  timeSpentSeconds: number;
  quizAttempted: boolean;
  quizScore: number;
  fireLevel: 'Super Fire 🔥' | 'Small Flame 🔥' | 'Last Bench 📉' | null;
  aiNotesContent?: string;
}

export interface DynamicModule {
  id: string;
  title: string;
  topics: DynamicTopic[];
}

export interface CustomRoadmap {
  id: string;
  title: string;
  topicPrompt: string;
  status: 'In Progress' | 'Completed';
  overallProgress: number;
  totalStreak: number;
  totalPoints: number;
  modules: DynamicModule[];
  createdAt: Date;
}

export interface UserGamificationState {
  currentStreak: number;
  totalPoints: number;
  badges: string[];
}

@Injectable({
  providedIn: 'root'
})
export class RoadmapService {
  // In-memory mock of our MongoDB Collections
  private userRoadmaps: Map<string, CustomRoadmap> = new Map();
  private userState: UserGamificationState = {
    currentStreak: 12,
    totalPoints: 4200,
    badges: ['Focus God ⏱️']
  };

  constructor() {}

  /**
   * Simulates sending a prompt to the LLM backend to generate a Zero-to-Hero roadmap.
   */
  generateRoadmap(prompt: string): Observable<CustomRoadmap> {
    const roadmapId = 'rm_' + Math.random().toString(36).substr(2, 9);
    
    // Create a deeply nested mock generated by the "AI" based on the prompt
    const newRoadmap: CustomRoadmap = {
      id: roadmapId,
      title: `${prompt.substring(0, 15).toUpperCase()} Zero-to-Hero`,
      topicPrompt: prompt,
      status: 'In Progress',
      overallProgress: 0,
      totalStreak: 0,
      totalPoints: 0,
      createdAt: new Date(),
      modules: [
        {
          id: 'm1',
          title: 'Module 1: The Absolute Basics',
          topics: [
            { id: 't1_1', title: 'What actually is it?', isRead: false, timeSpentSeconds: 0, quizAttempted: false, quizScore: 0, fireLevel: null },
            { id: 't1_2', title: 'Why should you care?', isRead: false, timeSpentSeconds: 0, quizAttempted: false, quizScore: 0, fireLevel: null },
            { id: 't1_3', title: 'Setup & Installation', isRead: false, timeSpentSeconds: 0, quizAttempted: false, quizScore: 0, fireLevel: null },
          ]
        },
        {
          id: 'm2',
          title: 'Module 2: Core Concepts (Mains)',
          topics: [
            { id: 't2_1', title: 'The Architecture', isRead: false, timeSpentSeconds: 0, quizAttempted: false, quizScore: 0, fireLevel: null },
            { id: 't2_2', title: 'Key Algorithms & Logic', isRead: false, timeSpentSeconds: 0, quizAttempted: false, quizScore: 0, fireLevel: null },
            { id: 't2_3', title: 'Common Pitfalls', isRead: false, timeSpentSeconds: 0, quizAttempted: false, quizScore: 0, fireLevel: null },
          ]
        },
        {
          id: 'm3',
          title: 'Module 3: Advanced "Chad" Topics',
          topics: [
            { id: 't3_1', title: 'Performance Optimization', isRead: false, timeSpentSeconds: 0, quizAttempted: false, quizScore: 0, fireLevel: null },
            { id: 't3_2', title: 'Real-world Scaling', isRead: false, timeSpentSeconds: 0, quizAttempted: false, quizScore: 0, fireLevel: null },
          ]
        }
      ]
    };

    // Store in our mock DB dict
    this.userRoadmaps.set(roadmapId, newRoadmap);

    // Return via observable with delay to simulate heavy LLM text stream
    return of(newRoadmap).pipe(delay(2500));
  }

  getRoadmap(id: string): CustomRoadmap | undefined {
    return this.userRoadmaps.get(id);
  }

  getAllRoadmaps(): CustomRoadmap[] {
    return Array.from(this.userRoadmaps.values());
  }

  /**
   * Simulates hitting the LLM API to fetch specific hinglish markdown
   */
  fetchTopicNotes(topicId: string, promptInfo: string, language: 'English' | 'Hinglish'): Observable<string> {
    let content = '';
    if (language === 'Hinglish') {
        content = `**Bhai sun:** Tu jo sikhna chahta hai (*${promptInfo}*), yeh topic uska fundamental base hai! \n\nAsal life mein, jab hum complex problems face karte hain, we need clear architecture. \n\n*Pro Tip:* Isko skip mat karna varna practically kuch apply nahi kar paega.`;
    } else {
        content = `**Core Overview:** Understanding the core fundamentals of *${promptInfo}*.\n\nIn industry applications, mastering this foundational architectural piece separates Junior developers from Senior engineers.\n\n*Pro Tip:* Ensure you fully grasp this before advancing.`;
    }
    return of(content).pipe(delay(1000));
  }
  
  // Gamification tracking mutations
  updateTopicAsRead(roadmapId: string, topicId: string): void {
    const roadmap = this.userRoadmaps.get(roadmapId);
    if (!roadmap) return;
    
    // Deep search to mark as read
    roadmap.modules.forEach(m => {
      const topic = m.topics.find(t => t.id === topicId);
      if (topic && !topic.isRead) {
        topic.isRead = true;
        roadmap.totalPoints += 50; // Give points for reading
      }
    });
  }

  submitQuizResult(roadmapId: string, topicId: string, score: number): void {
     const roadmap = this.userRoadmaps.get(roadmapId);
     if (!roadmap) return;
     
     roadmap.modules.forEach(m => {
       const topic = m.topics.find(t => t.id === topicId);
       if (topic) {
         topic.quizAttempted = true;
         topic.quizScore = score;
         if (score === 5) {
           topic.fireLevel = 'Super Fire 🔥';
           this.userState.currentStreak += 2;
           roadmap.totalStreak += 2;
           roadmap.totalPoints += 150;
         } else if (score >= 3) {
           topic.fireLevel = 'Small Flame 🔥';
           this.userState.currentStreak += 1;
           roadmap.totalStreak += 1;
           roadmap.totalPoints += 50;
         } else {
           topic.fireLevel = 'Last Bench 📉';
         }
       }
     });
  }

  getUserState(): UserGamificationState {
    return this.userState;
  }
}
